{
  "openapi": "3.0.0",
  "info": {
    "title": "StubHub Sales API",
    "version": "2.249.0.0",
    "x-logo": {
      "url": "https://img.vggcdn.net/images/Assets/Icons/bfx/stubhub-logo-merch-purple-mweb.440b3765.svg",
      "backgroundColor": "#222222"
    }
  },
  "servers": [
    {
      "url": "https://api.stubhub.net/v2",
      "description": "Production"
    },
    {
      "url": "https://sandbox.api.stubhub.net/v2",
      "description": "Sandbox"
    }
  ],
  "paths": {
    "/sales/{saleId}/shipments/{shipmentId}/label": {
      "get": {
        "tags": [
          "Shipments"
        ],
        "summary": "Get shipping label for a sale",
        "operationId": "Shipments_GetSaleShippingLabel",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}/shipments": {
      "get": {
        "tags": [
          "Shipments"
        ],
        "summary": "List shipments for a sale",
        "operationId": "Shipments_GetSaleShipments",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Shipments"
        ],
        "summary": "Print a shipping label for a sale",
        "operationId": "Shipments_PutOrGetSaleShipmentLabel",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sales"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}/shipments/{shipmentId}": {
      "patch": {
        "tags": [
          "Shipments"
        ],
        "summary": "Update a shipment for a sale",
        "operationId": "Shipments_PatchSaleShipment",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sales"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}/eticketuploads": {
      "post": {
        "tags": [
          "E-Tickets"
        ],
        "summary": "Upload e-tickets or proof of transfer for a sale",
        "description": "Once the PDFs has been successfully been uploaded, you must also patch the sale confirming which pages of each PDF should be saved against the order. To do this, the Ids of the etickets property embedded in the EticketUploadEmbeddedResources of each upload, and patch the sale with those Ids.",
        "operationId": "ETicket_UploadSaleETicket",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sales"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "E-Tickets"
        ],
        "summary": "List e-ticket uploads for a sale",
        "operationId": "ETicket_GetSaleETicketUploads",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}/etickets": {
      "get": {
        "tags": [
          "E-Tickets"
        ],
        "summary": "List e-tickets for a sale",
        "operationId": "ETicket_GetSaleETickets",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}/etickets/{eticketId}": {
      "delete": {
        "tags": [
          "E-Tickets"
        ],
        "summary": "Delete e-ticket from a sale",
        "operationId": "ETicket_DeleteSaleETicket",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sales"
            ]
          }
        ]
      }
    },
    "/sales/recentupdates": {
      "get": {
        "tags": [
          "Sales"
        ],
        "summary": "List sales (recent updates)",
        "description": "List sales for the authenticated user that have been created or updated over a certain period of time.",
        "operationId": "Sales_GetSalesRecentUpdates",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      }
    },
    "/sales": {
      "get": {
        "tags": [
          "Sales"
        ],
        "summary": "List sales",
        "description": "List sales for the authenticated user.",
        "operationId": "Sales_GetSales",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}": {
      "get": {
        "tags": [
          "Sales"
        ],
        "summary": "Get a sale",
        "operationId": "Sales_Get",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Sales"
        ],
        "summary": "Update a sale",
        "operationId": "Sales_Patch",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sales"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Sales"
        ],
        "summary": "Reject a sale",
        "description": "Report a problem with a sale of tickets.",
        "operationId": "Sales_Delete",
        "security": [
          {
            "OAuth2": [
              "write:user",
              "write:sales"
            ]
          }
        ]
      }
    },
    "/payments": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "List payments",
        "description": "Lists payments for the authenticated user.",
        "operationId": "Payments_GetPayments",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:payment"
            ]
          }
        ]
      }
    },
    "/payments/{paymentId}": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Get a payment",
        "operationId": "Payments_Get",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:payment"
            ]
          }
        ]
      }
    },
    "/payments/next": {
      "get": {
        "tags": [
          "Payments"
        ],
        "summary": "Preview next payment",
        "description": "Previews the next payment for the authenticated user. The payment will not have an `id` and is subject to changes.",
        "operationId": "Payments_GetNextPayment",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:payment"
            ]
          }
        ]
      }
    },
    "/etickets/{eticketId}/thumbnail": {
      "get": {
        "tags": [
          "E-Tickets"
        ],
        "summary": "Get e-ticket thumbnail file",
        "description": "Download an image file containing a thumbnail of an E-Ticket",
        "operationId": "ETicketDocument_GetETicketThumbnail",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/eticketuploads/{eticketUploadId}/document": {
      "get": {
        "tags": [
          "E-Tickets"
        ],
        "summary": "Get e-ticket upload file",
        "description": "Download the original file that was uploaded.",
        "operationId": "ETicketDocument_GetETicketUploadDocument",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/etickets/{eticketId}/document": {
      "get": {
        "tags": [
          "E-Tickets"
        ],
        "summary": "Get e-ticket file",
        "description": "Download a PDF file containing an E-Ticket.",
        "operationId": "ETicketDocument_GetETicketDocument",
        "security": [
          {
            "OAuth2": [
              "read:user"
            ]
          }
        ]
      }
    },
    "/sales/{saleId}/ticketholders": {
      "get": {
        "tags": [
          "TicketHolders"
        ],
        "summary": "List ticket holder details for a sale",
        "operationId": "TicketHolders_GetSaleTicketHolderDetails",
        "security": [
          {
            "OAuth2": [
              "read:user",
              "read:sales"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "bearerFormat": "JWT",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://account.stubhub.com/authorize",
            "tokenUrl": "https://account.stubhub.com/oauth2/token",
            "refreshUrl": "https://account.stubhub.com/oauth2/token"
          },
          "clientCredentials": {
            "tokenUrl": "https://account.stubhub.com/oauth2/token"
          },
          "authorizationCode": {
            "authorizationUrl": "https://account.stubhub.com/authorize",
            "tokenUrl": "https://account.stubhub.com/oauth2/token",
            "refreshUrl": "https://account.stubhub.com/oauth2/token"
          }
        }
      }
    }
  },
  "security": [
    {
      "OAuth2": [
        "read:payment",
        "read:sales",
        "read:sellerlistings",
        "read:user",
        "write:purchases",
        "write:sales",
        "write:sellerlistings",
        "write:user"
      ]
    }
  ],
  "tags": [
    {
      "name": "BasicType_Money",
      "description": "Returned for monetary values, such as ticket prices, fees charged and tax amounts.\n<SchemaDefinition schemaRef=\"#/components/schemas/Money\" showReadOnly={true} showWriteOnly={true} />",
      "x-displayName": "Money"
    },
    {
      "name": "BasicType_Seating",
      "description": "Represents the seating information for a ticket(s) in a Venue.\n<SchemaDefinition schemaRef=\"#/components/schemas/Seating\" showReadOnly={true} showWriteOnly={true} />",
      "x-displayName": "Seating"
    },
    {
      "name": "E-Tickets"
    },
    {
      "name": "Payments"
    },
    {
      "name": "Resource_ETickets",
      "description": "\n<SchemaDefinition schemaRef=\"#/components/schemas/ETickets\" showReadOnly={true} showWriteOnly={true} />",
      "x-displayName": "ETickets"
    },
    {
      "name": "Resource_ETicketUploads",
      "description": "\n<SchemaDefinition schemaRef=\"#/components/schemas/ETicketUploads\" showReadOnly={true} showWriteOnly={true} />",
      "x-displayName": "ETicketUploads"
    },
    {
      "name": "Resource_Payment",
      "description": "A payment on the StubHub marketplace that belongs to the currently authenticated user.\n<SchemaDefinition schemaRef=\"#/components/schemas/Payment\" showReadOnly={true} showWriteOnly={true} />",
      "x-displayName": "Payment"
    },
    {
      "name": "Resource_Payments",
      "description": "\n<SchemaDefinition schemaRef=\"#/components/schemas/Payments\" showReadOnly={true} showWriteOnly={true} />",
      "x-displayName": "Payments"
    },
    {
      "name": "Resource_Sale",
      "description": "A sale on the StubHub marketplace that belongs to the currently authenticated user.\n<SchemaDefinition schemaRef=\"#/components/schemas/Sale\" showReadOnly={true} showWriteOnly={true} />",
      "x-displayName": "Sale"
    },
    {
      "name": "Resource_Sales",
      "description": "\n<SchemaDefinition schemaRef=\"#/components/schemas/Sales\" showReadOnly={true} showWriteOnly={true} />",
      "x-displayName": "Sales"
    },
    {
      "name": "Resource_Shipment",
      "description": "A shipment of one or more tickets by a seller.\n<SchemaDefinition schemaRef=\"#/components/schemas/Shipment\" showReadOnly={true} showWriteOnly={true} />",
      "x-displayName": "Shipment"
    },
    {
      "name": "Resource_Shipments",
      "description": "The Shipments resource is a collection resource that contains zero or\nmore references to a set of shipments, and links that guide you on ways\nto interact with the shipments. The collection offers a paginated view\nof shipments.\n<SchemaDefinition schemaRef=\"#/components/schemas/Shipments\" showReadOnly={true} showWriteOnly={true} />",
      "x-displayName": "Shipments"
    },
    {
      "name": "Resource_TicketHolder",
      "description": "\n<SchemaDefinition schemaRef=\"#/components/schemas/TicketHolder\" showReadOnly={true} showWriteOnly={true} />",
      "x-displayName": "TicketHolder"
    },
    {
      "name": "Sales",
      "description": "View your sales details and fulfill your sales."
    },
    {
      "name": "Shipments"
    },
    {
      "name": "TicketHolders"
    }
  ],
  "x-tagGroups": [
    {
      "name": "Endpoints",
      "tags": [
        "Sales",
        "E-Tickets",
        "Payments",
        "Shipments",
        "TicketHolders"
      ]
    },
    {
      "name": "Basic Types",
      "tags": [
        "BasicType_Money",
        "BasicType_Seating"
      ]
    },
    {
      "name": "Resources",
      "tags": [
        "Resource_ETickets",
        "Resource_ETicketUploads",
        "Resource_Payment",
        "Resource_Payments",
        "Resource_Sale",
        "Resource_Sales",
        "Resource_Shipment",
        "Resource_Shipments",
        "Resource_TicketHolder"
      ]
    }
  ]
}